### ISSUE TITLE
[Meeting] Form meeting (April 8th)

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/i#22]
### 🙋 Participants

@acmcsufoss/form 

### 📍 Meeting location

Open Source Software team VC

### 🗓️ Meeting date and time

Apr 8th, 2024 10:00 PM

### ⏱️ Estimated meeting duration

60 minutes

### 📋 Meeting agenda

- Welcome new and returning participants.

### 🚀 Meeting updates

- School came back from Spring Break today.
- Solar eclipse happened earlier today.
- Nintendo shut down the 3DS and Wii U servers earlier today.

### Notes
- Question input editors number, boolean, color are behaving, just not styled yet.
- <https://developer.mozilla.org/en-US/docs/Web/API/FormData/getAll>
- We are using fieldsets and legends over labels in question input components because not every question is composed of only one input element; sometimes they contain multiple input elements that are intended to be grouped together.

### 😸 Action items

Tasks up for progress review on Thursday:

### TODO(@EthanThatOneKid): Look into dragging and dropping to reorder list of questions in list editor.
- Reference: <https://svelte.dev/repl/2cf25d5fd92b4163a356679c4315d386?version=3.15.0>.
- Note: Fix select question editor component.

### TODO(@keillor): Finalize input editor components.
- [ ] Date
- [ ] Datetime
- [ ] Time
- [ ] Text
- [ ] Textarea

### TODO(@AlexthePear):
- [ ] Refactor question input components to labels and fix styling.
- [ ] Move question input container into component with slot.
- [ ] Number
- [ ] Boolean
- [ ] Color
- [ ] Timezone
- [ ] Availability (blocked on list input)
- [ ] Radiogroup (block on list input)

### ✨ Meeting wrap-up

- Next meeting: Thursday at 4:00 PM!
- Adjournment time: 12:20 AM
